apiVersion: v1
kind: Service
metadata:
  name: chars-info

spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: chars
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: chars
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chars
  template:
    metadata:
      labels:
        app: chars
    spec:
      containers:
        - name: chars
          image: "127.0.0.1:30400/chars-inf:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081