apiVersion: v1
kind: Service
metadata:
  name: chars-info
  labels:
    app: app
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "127.0.0.1:30400/chars-inf"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000